version: 2.1

jobs:
  build-master:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run:
          name: ビルド
          command: ./gradlew build
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: ~/project/build/libs/XCore.jar
      - run:
          name: フィンガープリント登録
          command: echo 'play.craft.xeltica.work,172.105.242.153 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHi9ZWNTLt55UEnlid3bWIryFIGhLtI249vL0R8WsYvQ8RY5dSeyr11BvqS0WvYnpTWzmNFBmuoKrgn65YoGZwk=' >> ~/.ssh/known_hosts;
      - run:
          name: 秘密鍵登録
          command:
            echo 'Host play.craft.xeltica.work' > ~/.ssh/config;
            echo '  IdentityFile /home/circleci/.ssh/id_rsa_d21b72bd6cb7d6ef41501c73ddf084bb' >> ~/.ssh/config;
            echo '  User xeltica' >> ~/.ssh/config;
            cat ~/.ssh/config;
      - run:
          name: LFTPのインストール
          command: sudo apt-get update && sudo apt-get install lftp
      - run:
          name: サーバーへのプラグインのアップロード
          command: mkdir p && mv ./build/libs/XCore.jar p && cd p && lftp -e "mirror -R --only-newer . /srv/papermc/plugins && exit" sftp://play.craft.xeltica.work
      - run:
          name: サーバーへのプラグインのインストール
          command: ssh xeltica@play.craft.xeltica.work 'sh /srv/deploy-core.sh'

workflows:
  build:
    jobs:
      - build-master:
          filters:
            branches:
              only:
                - master
